### ISSUE TITLE
Bug: corrección de tamaño  de fotografia

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#100]
se debe corregir el tamaño de la fotografia de Ana en el bento de la  page aboutme, es muy grande y se puede bajar al tamaño que adopta en la versión mobile 

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/c9b28b56-2064-4e06-9911-3ce9b29d799a)

**Comment by felixicaza** [comment]
Esto podría estar solucionado en la PR #109, dónde optimicé las imágenes que eran muy grandes y ahora tienen un tamaño adecuado.

**Comment by Zyruks** [comment]
Ahora si se soluciono ;)
