### ISSUE TITLE
Agregar img y descripción  de cuando se comparte el link de la web

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#102]
Actualmente cuando se comparte el link del sitio web no aparece la descripción de la web ni la imagen de cover , ana debe crearla

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/2ba590bd-e599-4366-a1c1-9e493e190ec9)

**Comment by felixicaza** [comment]
Se resolvió en #98.
