### ISSUE TITLE
componente de contactame

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#11]
## Descripción 

Crear el componente final donde el usuario puede contactar Ana

## Criterio de aceptación:

- Contener el texto y ambos botones (los botones no tienen que estar funcionales)
- Deber funcionar responsive

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/56b2ddaf-804e-4898-9319-4c4114de651f)

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/72ab8126-e208-413b-937b-af6e11adbc8e)

**Comment by luis-codex** [comment]
Hola @AnaRangel,

He visto la issue #11 sobre la creación del componente de contactame. Me gustaría encargarme de esta tarea.

Si hay detalles adicionales que deba tener en cuenta mientras trabajo en esto, por favor házmelo saber.
