### ISSUE TITLE
Corregir alineación en responsive PR #79

### ISSUE THREAD

**Issue by odracirdev** [AnaRangel/anarangel.github.io#115]
En el PR #79 se debe corregir la alineación de los elementos ya que están muy pegados a la izquierda.

![image](https://github.com/AnaRangel/anarangel.github.io/assets/84311660/27232daa-223b-460c-b0e8-0bc345a2efe7)

**Comment by felixicaza** [comment]
Gracias @odracirdev, lo corrijo.
