### ISSUE TITLE
Bug: Scroll horizontal en pantallas de 768px a 1038px en página "Sobre mi"

### ISSUE THREAD

**Issue by Alais29** [AnaRangel/anarangel.github.io#117]
En pantallas medianas existe un scroll horizontal que se debe a la disposición de las imágenes en la tarjeta de "Voluntariado" 

![image](https://github.com/AnaRangel/anarangel.github.io/assets/28829550/d5170090-deac-4c6f-8d33-16fd998bc46d)

**Comment by GountzJs** [comment]
pa mi

**Comment by Zyruks** [comment]
@GountzJs Tarde :V Done
