### ISSUE TITLE
Efecto aurora por detrás del componente de contactame

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#12]
## Descripción

Crear efecto aurora que va por detrás del componente de contacto, este efecto solo es para dispositivos desktop

## Criterio de aceptación

- El efecto debe contener la paleta de colores que está en el figma 

| Color             | Hex                                                                |
| ----------------- | ------------------------------------------------------------------ |
| Degradado Azul| background: radial-gradient(48.42% 48.42% at 49.41% 51.58%, rgba(14, 0, 79, 0.82) 0%, rgba(0, 0, 0, 0.00) 100%) |
| Degradado violeta| background: radial-gradient(48.42% 48.42% at 49.41% 51.58%, rgba(148, 82, 255, 0.40) 0%, rgba(0, 0, 0, 0.00) 100%); |
| Degradado beige| background: radial-gradient(48.42% 48.42% at 49.41% 51.58%, rgba(237, 143, 158, 0.32) 0%, rgba(0, 0, 0, 0.00) 100%);|

- De ser posible que contenga dinamismo y cambio de color, de ejemplo esta codepen https://codepen.io/amyth91/pen/DzYGaK
- No es necesario que sea responsive

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/c8ab574a-8c61-4d10-a342-42f5828c03c6)

**Comment by luis-codex** [comment]
Hola @AnaRangel,

He visto la issue #12 sobre la creación del Efecto aurora. Me gustaría encargarme de esta tarea.

Si hay detalles adicionales que deba tener en cuenta mientras trabajo en esto, por favor házmelo saber.
