### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#13]
## Descripción

Hacer ajustes para el componente del footer

#Criterios de aceptación

- Ajustar espaciados y dimensiones de los elementos
- Que sea funcional en responsive
- No es necesario que esten linkeadas las redes sociales

Fotos del figma:

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/213e9f11-a429-4b7e-81e2-186d4c765547)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/125841be-3af7-4665-8249-ba174c305470)

Ya el componente está creado dentro del proyecto
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/2e002ef7-dba5-42a5-bf7a-c977164becc5)

**Comment by Martingomez092** [comment]
Me gustaría trabajar sobre esto!
