### ISSUE TITLE
Center the footer text

### ISSUE THREAD

**Issue by colmedev** [AnaRangel/anarangel.github.io#131]
![image](https://github.com/AnaRangel/anarangel.github.io/assets/161905693/645f3457-414c-4ebd-952c-5b56d2f4dfd3)

**Comment by felixicaza** [comment]
Esto ya está corregido.
![image](https://github.com/AnaRangel/anarangel.github.io/assets/38303370/911c9d99-bc0f-41ca-8db8-9242a5845fdb)
