### ISSUE TITLE
Logo no aparece en Iphone

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#156]
En iphone desaparece el logo de Ana :(

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/538bdc38-a546-4b39-881b-160799e04e27)

**Comment by felixicaza** [comment]
@AnaRangel Duplicado de la issue #155.

**Comment by odracirdev** [comment]
Duplicada.
