### ISSUE TITLE
Arreglar posición de img

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#157]
Se debe arreglar la posición de la img de saber mas del proyecto (LATAM) que debe estar pegada abajo a la izquierda como en el figma 

Figma:

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/6c0f6558-e977-4955-95fa-f3e011db5aac)

Producción:

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/5a2d06e6-504e-4a86-8bc9-147352f025d5)

**Comment by colmedev** [comment]
la puedo pedir? :p
