### ISSUE TITLE
Arreglar responsive de botones

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#165]
Los botones en responsives deben ocupar el ancho de la pantalla con en el figma

Producción:
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/989ca1f2-f782-488e-b4b8-f3004e90aa5e)

Figma
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/db0b2962-c301-4059-980a-da72de1e5403)

**Comment by colmedev** [comment]
puedo ayudar? :p

**Comment by felixicaza** [comment]
@colmedev Si ❤️
