### ISSUE TITLE
Conectar botones en el call to action y el hero

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#17]
## Descripción

Se debe dejar funcionales los botones de contactame y dercargar cv

- Contactame: dee redireccionar a alguna app que sea para agendar reuniones con Ana (hay que buscar cuál sería la mejor opción)
- Descargar CV: se desacarga el PDF con el cv de Ana (considerar que debe haber un pdf para la versión en ingles de la web)

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/636a29b8-a19d-40c7-bb39-31abc35c651a)

**Comment by odracirdev** [comment]
La mejor opción gratuita que conozco para agendar una una reunión sería [Calendly](https://calendly.com/es).

**Comment by Alais29** [comment]
Como opción para calendario podrías tambien usar [Google Calendar Appointments](https://calendar.google.com/calendar/u/0/r/appointment)
