### ISSUE TITLE
Agregar iconos de tools flotantes al hero

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#19]
## Descripción 

Se deben agregar los svg de los logos de las tools de diseño que van en el hero, de ser posible se puede agregar un efecto donde estén flotando (es un ejemplo es a libre creatividad), considerar que esto no se ve en mobile

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/a31643d5-2d3f-40bb-b1c0-a6c378f4c8cd)

https://github.com/AnaRangel/anarangel.github.io/assets/30361612/0c6eec09-71c3-4968-ad9b-bd0a3f5b0e3e

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/cde08d25-cc84-4f5a-857d-3e3035af1534)

**Comment by felixicaza** [comment]
Esto es mío.
