### ISSUE TITLE
Creación del section contributers

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#20]
## Description 

Se debe crear la sección de los que han contribuido en el proyecto en desarrollo y diseño

## Criterios de aceptación:

Contribuidores en desarrollo: cada imagen de cada persona debe aparecer en cada circulo, deben ser cliqueables y redireccionar a los github de cada uno, se podría conectar con la api de github para obtener esa información.

Contribuidores en diseño: se debe crear hardcode por cada uno de los diseñadores que contribuyan, la imagen se debe sacar de linkedin y linkearlo

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/8d650095-ace7-4faf-9f3b-bd266956bbee)

**Comment by Facundodandrea** [comment]
Hola @AnaRangel,

He visto la issue #20  sobre la creación de la sección de contribuciones . Me gustaría encargarme de esta tarea.

Este es el avance que tengo por el momento.



![Image](https://github.com/AnaRangel/anarangel.github.io/assets/71223579/db25c9fa-5c28-4444-9875-28dcb2416703)

**Comment by AnaRangel** [comment]
@Facundodandrea se ve buenaaa te felicito :3 ! @Zyruks lo vera a nivel de codigo pero yo puedo agregar que le añadas un gap de 24px de separación entre elementos
