### ISSUE TITLE
Crear bento con la información de Ana en page sobre mi

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#21]
## Descripción 

Se debe crear el section de información de Ana que es un bento

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/5087128c-e68e-4a2e-b462-e6e48179bd75)

**Comment by Facundodandrea** [comment]
Hola @AnaRangel,

He visto la issue #21 sobre la creación del bento con la información básica . Me gustaría encargarme de esta tarea.
