### ISSUE TITLE
Section tools en page sobre mi

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#23]
## Descripción

Se debe crear la sección que muestra los tools de diseño que maneja Ana, considerar que sólo se busca que esté el diseño estático, en responsive sólo se debe redimensionar

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/3bf96908-a53c-4978-a87d-c0f71ee45378)

**Comment by felixicaza** [comment]
Me lo pido. Y al estar relacionado con #24, #25 y #26, podrías asignarme esta seccion en general.
