### ISSUE TITLE
Dashes animation

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#24]
En la sección de tools en la page sobre mi, los dash que conectan las herramientas con el logo de Ana deben tener un border animation que vaya hacia el centro del logo se deja una web de referencia --->>> https://www.create.video/

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/c8e96562-0546-40be-973c-4d47124f430f)

**Comment by felixicaza** [comment]
Esto es mío.
