### ISSUE TITLE
Colorfull animation

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#25]
en la section tools del page sobre mi, el logo de Ana que está en el centro debe tener un efecto de cambio de colores como en la referencia que se deja aquí --->>> https://www.create.video/

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/8bf3b99a-b379-4f9d-b54d-de80bf922cbe)

**Comment by felixicaza** [comment]
Esto es mío.
