### ISSUE TITLE
crear tooltip de herramientas de diseño

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#26]
Se debe crear la funcionalidad de cuando se haga hover sobre las herrmientas de diseño  salga un tooltip con los nombres de cada herramienta

https://github.com/AnaRangel/anarangel.github.io/assets/30361612/9e5856be-51d3-4fbb-ab8a-fd32479f285e

Whinsical
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/42f83df5-1569-44d4-b598-9d763cd6ee33)

Adobe xd
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/9376f942-4fac-4f2d-9ab6-ee7826eed889)

Hotjar
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/fd4c3d32-3c13-4af5-92d7-f179f0add7f2)

Maze
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/853ecac2-b90f-4218-ac20-2347d6b5b3b3)

Miro
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/0218879b-a7ee-4086-929d-87ae0efe9b71)

Figma
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/82e09cc0-cd5f-470b-9967-5fb47cc48ddc)

Notion
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/7e6a4859-8ff8-46dc-ac40-3d9639d57b00)

Useberry
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/ec8ef3b9-1b97-4119-80bb-e2fc609db9cc)

**Comment by felixicaza** [comment]
Esto es mío.

**Comment by felixicaza** [comment]
Esto es mío.
