### ISSUE TITLE
Crear section hobbies

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#27]
Crear sección de hobbies dentro de la page de about me, es un bento estático 

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/40ba28fe-f989-4dec-9286-3ca2d20b19a8)

**Comment by Facundodandrea** [comment]
Hola @AnaRangel,

He visto la issue #27 sobre la creación de la sección hobbies . Me gustaría encargarme de esta tarea.
