### ISSUE TITLE
Crear el componente de testimony card

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#28]
Se debe crear el componente de la card para testimonios, esto incluye crear un objeto para recibir la información que va a alimentar cada card

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/f930cecd-5952-4e85-9dcf-b149f814fae4)

**Comment by luis-codex** [comment]
Hola @AnaRangel,

He visto la issue #28 sobre la creación del componente de la tarjeta de testimonios. Me gustaría encargarme de esta tarea. Crearé un objeto para recibir la información que alimentará a la tarjeta, tal como lo especificaste. 

Si hay detalles adicionales que deba tener en cuenta mientras trabajo en esto, por favor házmelo saber.

**Comment by AnaRangel** [comment]
@luis-codex vale no hay problema :) igual esta tarea tambien implica la UI pero te dejo el css de la card :)  

border-radius: 24px;
border: 1px solid #282828;
background: #0D0D0E;

display: flex;
width: 325px;
height: 428px;
padding: 24px;
flex-direction: column;
align-items: flex-start;
gap: 24px;
