### ISSUE TITLE
Crear testimony section

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#29]
crear la sección de testimonios de personas que han trabajado con Ana

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/89a65c0e-6e73-4c5e-9b0a-8a367e195784)

**Comment by luis-codex** [comment]
Hola @AnaRangel,

He visto la issue #29 sobre la creación de la seccion de testimonios. Me gustaría encargarme de esta tarea.

Si hay detalles adicionales que deba tener en cuenta mientras trabajo en esto, por favor házmelo saber.
