### ISSUE TITLE
Crear carrusel de testimonios

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#30]
Se debe crear animación de transición de las cards igual a la de Betback -->>https://betback.io/

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/8374aabe-13da-468a-9024-3b81c822e081)

**Comment by AnaRangel** [comment]
@luis-codex te asiganre esta card en vista de que estas avanzando :) necesito que comentes para poder hacerlo

**Comment by luis-codex** [comment]
Hola @AnaRangel,

He visto la issue #30 sobre la creación del carrusel de testimonios . Me gustaría encargarme de esta tarea.

Si hay detalles adicionales que deba tener en cuenta mientras trabajo en esto, por favor házmelo saber.
