### ISSUE TITLE
header component case study

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#31]
## Descripción 

Se debe crear el componente de header que tiene el logo, título y texto de resumen que va a cambiar por cada caso de estudio

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/62f4d2b1-7a61-473e-82f9-7449d5663f29)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/40ae63c5-31c2-415b-8fe9-1c72165164da)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/0a5a4d1b-97bf-47b9-a5a6-36f4919f6682)

**Comment by felixicaza** [comment]
Esto es mío.
