### ISSUE TITLE
crear componente con cards information

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#32]
## Descripción

Se debe crear el componente con las tres cards con la información base del proyecto  este componente se repite en todas las page de caso de estudio

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/ea036990-3639-490e-bb01-7b832265d7c9)

**Comment by Zyruks** [comment]
Para esto pueden usar CardWrapper
