### ISSUE TITLE
Crear component content

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#33]
Se debe crear el componente que engloba el contenido de titulo, texto e imagen, es utilizado repetidas veces en todas las pages de caso de estudio

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/becb6f58-d8a5-429e-9845-29ab84ab6fd0)

**Comment by luis-codex** [comment]
Hola @AnaRangel,

He visto la issue #33 sobre la creación del component content. Me gustaría encargarme de esta tarea.

Si hay detalles adicionales que deba tener en cuenta mientras trabajo en esto, por favor házmelo saber.
