### ISSUE TITLE
Crear card image component

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#34]
## Descripción 

Se debe crear el componente de card e imagenes donde hay diferentes variaciones de estilos

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/1c7202e4-5bc2-4389-ae6e-086331587119)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/d12421cd-228c-4b7b-a9e7-e1abf28ccfd0)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/fd24f061-e1ae-48df-974d-1f991db50acf)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/2e390e4d-c28a-4f31-8d6a-b609b1b4e7b5)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/3e4b7071-3b51-45c5-a061-1eed525ffce8)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/879e5ab4-41ae-4fb4-8836-48209817e1d9)

**Comment by luis-codex** [comment]
Hola @AnaRangel,

He visto la issue https://github.com/AnaRangel/anarangel.github.io/issues/34 sobre la creación del image component. Me gustaría encargarme de esta tarea.


Si hay detalles adicionales que deba tener en cuenta mientras trabajo en esto, por favor házmelo saber.

**Comment by AnaRangel** [comment]
@luis-codex usa el card wraper para poder hacer este issue
