### ISSUE TITLE
Thunder Card

### ISSUE THREAD

**Issue by colmedev** [AnaRangel/anarangel.github.io#42]

**Comment by AnaRangel** [comment]
Se debe crear la card con el contenido del Design system Thunder, esta card debe estar dentro de la sección del bento que están en el home 



![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/23596401-314c-45fa-9a80-4e4a3c48879c)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/bcfef74b-522b-44dd-a5c4-2f909976469b)

**Comment by felixicaza** [comment]
Solucionado en #107.
