### ISSUE TITLE
Crear cards de el caso de estudio de Latam

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#46]
Se dbee crear el ultimo elemento del bento que se encuentra en el home

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/1bc8fa83-5a18-408a-acde-fe652b50b34d)

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/af14edfd-b64e-4baf-ab3a-2ab721e5b295)

**Comment by felixicaza** [comment]
Esto es mío.
