### ISSUE TITLE
Hover sobre las marcas en el bento de charlas

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#53]
Se debe replicar el mismo hover del componente tools sobre las herramientas, en las marcas que se encuentran en el bento, especificamente en las charlas 

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/ec225723-8698-4ae6-a587-41077518fc23)

Deseafío Latam
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/0f62a10d-e97a-43a7-8116-a0244e8770cf)

Sparkcode
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/3a27d744-3a7c-476e-9305-a0fb7a03be85)

Javascript Chile
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/9e3f7773-25f3-4da8-ae17-38d6044b04ef)

4 geeks Academy
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/1bd3082c-2a75-499d-871d-b59db4d05d23)

**Comment by odracirdev** [comment]
Señor TL @Zyruks primero que nada permitame saludarlo con mucho respeto. Tenemos una duda técnica respecto a este issue y nos gustaría coordinar alguna reunión para discutir al respecto (se vale llevar cuchillos o cualquier tipo de arma cortopunzante, solo por si acaso).

El tema es: Hay dos maneras de crear el tooltip que quiere @AnaRangel, la primera y más fácil es hacerlo de forma nativa con la propiedad "title" de HTML  modificando sus estilos. La segunda y con mejor mantenibilidad es creando un componente nuevo.

Agradeceríamos mucho que se pusiera en contacto con nosotros para resolver esta situación.

Con mucho amor para nuestro TL favortito sin importar que no sea el TL del que Ana tanto habla. ❤️
