### ISSUE TITLE
Arreglo del estilo del menu en responsive

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#58]
Se debe ajustar los textos del menu que estén centrados como en el figma

###figma
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/0853ace7-a412-46b2-b0e1-94ca09b353c4)

###Implementado
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/d6e8c6f3-6496-4196-8c60-696d63a80045)

**Comment by felixicaza** [comment]
Quiero esto. 🥹

**Comment by felixicaza** [comment]
Se me adelantó @GountzJs y lo corrigió en #110. 😄
