### ISSUE TITLE
Agregar background blur al navbar

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#61]
Se debe agregar el background que le falta la navbar para que se pueda leer las opciones del menu cuando se haga scroll en las pages

### Integrado

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/2abcbed1-cb1a-42b7-b1ea-03b1eee7b22d)

### figma

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/4b93500e-d1cf-4af8-b5f5-10f42ec196a3)

**Comment by GountzJs** [comment]
esta task pa mi!
