### ISSUE TITLE
Gradient Background

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#7]
## Descripción:

Crear hero section interativo por sección

## Criterio de aceptación:

- Que por cada vista se le pase un parámetro del color correspondiente de cada sección:  

| Sección             | CSS                                                               |
| ----------------- | ------------------------------------------------------------------ |
| Home |background: radial-gradient(48.42% 48.42% at 49.41% 51.58%, rgba(46, 88, 255, 0.34) 0%, rgba(0, 0, 0, 0.00) 100%) |
| About me | background: radial-gradient(48.42% 48.42% at 49.41% 51.58%, rgba(148, 82, 255, 0.40) 0%, rgba(0, 0, 0, 0.00) 100%) |
| Ripley | background: radial-gradient(48.42% 48.42% at 49.41% 51.58%, #1E0D4F 0%, rgba(0, 0, 0, 0.00) 100%) |
| Latam| background: radial-gradient(48.42% 48.42% at 49.41% 51.58%, #061962 0%, rgba(0, 0, 0, 0.00) 100%); |
| Cencosud| background: radial-gradient(35.82% 35.18% at 50.01% 50%, rgba(48, 183, 202, 0.30) 0%, rgba(33, 212, 155, 0.00) 100%); |

- Debe funcionar en responsive

## Colores de referencia

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/e7b777df-8165-405d-b0c1-f885eb63213e)

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/a7ab01a2-8503-4556-a3eb-5ce2d3e6e45b)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/b76931f0-5e50-4516-9e1f-0b325e03982d)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/5b3d0b84-8d2c-436b-9709-0731fb5a50b0)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/289fb9b4-5025-4780-880b-8110ac38c298)

## Responsive

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/d76e4150-d84d-4292-9b8b-e1e3c0211c33)

**Comment by Facundodandrea** [comment]
Hola @AnaRangel,

He visto la issue #7 sobre la creación del  fondo gradiente . Me gustaría encargarme de esta tarea.
