### ISSUE TITLE
crear page de proyecto censoud

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#82]

**Comment by AnaRangel** [comment]
Se debe crear el page con todo el contenido y componentes, debe ser responsivo la pagina completa



![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/f1d39e21-5bfe-4a25-9aab-ae72d0c273d6)

**Comment by colmedev** [comment]
*quack*
