### ISSUE TITLE
Componente roles css home

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#9]
## Descripción:

Creación de imagen en css de la descripción de los roles de ana, ya  Tyto creo el estilo del marco con un efecto adicional cuando haces hover https://codepen.io/jagcruz/pen/gOJMyZV

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/128fd552-cd8c-4a57-a07a-233243c5e0b3)

Ya el proyecto tiene avanzada la mayoría de esta estructura, está en profession.astro, dentro de un article

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/8c74df63-374b-4714-8240-109f2a846bf3)

**Comment by odracirdev** [comment]
Test
