### ISSUE TITLE
Bug: arreglo de cambio de colores en el modo dark de los navegadores

### ISSUE THREAD

**Issue by AnaRangel** [AnaRangel/anarangel.github.io#96]
##Descripción 

Se detectó que en los dispositivos que cambian de modo dark o light cambian los colores de la tipografía y los elementos de la web, se debe mantener que la web sea modo dark

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/db999b6a-8124-41e8-84cc-5cf50d2166cf)
![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/89b102bf-8d6c-4249-97c7-7b2273a2d9a7)

![Image](https://github.com/AnaRangel/anarangel.github.io/assets/30361612/237c08aa-f84d-48d4-b61a-147dc75c7e38)

**Comment by felixicaza** [comment]
Con la primera captura, se tendría que ver que versión de navegador se está usando, ya que se ve que no renderiza bien los SVG ni los colores de los gradientes. 😄

Para la captura de móvil acabo de comprobar que se tiene el mismo error con los colores de algunos títulos.

**Comment by felixicaza** [comment]
Esto debería estar solucionado con la PR #129. Por favor confirmar.
